name: Update Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
jobs:
  update:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - name: Update Wakatime
        uses: athul/waka-readme@master
        with:
           IGNORED_LANGUAGES: Binary XML JSON Bash Bash INI Batchfile Markdown "Git Config" Other
           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
           #TIME_RANGE: all_time
           CODE_LANG: fs
           #SHOW_TITLE: true
           LANG_COUNT: 5
           SHOW_TOTAL: true
           SHOW_TIME: true
      - name: Update snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          palette: github-dark
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
